In [85]:
HDILink1="https://docs.google.com/spreadsheets/d/e/2PACX-1vSp6si_gYJcZP5BMHVPp38FW0IaqH6uNkhHYVII2fKukg8jAMANm0tsDYzHyr0N_Q/pub?output=csv"

import pandas as pd
HDI=pd.read_csv(HDILink1)
HDI

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
HDI.columns

Index(['Back', 'Table 1. Human Development Index and its components ',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [87]:
keep=['Back','Table 1. Human Development Index and its components ','Unnamed: 2','Unnamed: 4','Unnamed: 6','Unnamed: 8','Unnamed: 10','Unnamed: 12','Unnamed: 14']
dontKeep=set(HDI.columns.to_list())-set(keep)
HDICleaned=HDI.drop(columns=dontKeep)
HDICleaned

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
HDICleaned.loc[:,keep]

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
change={"Back":"HDI rank",'Table 1. Human Development Index and its components ':"Country","Unnamed: 2":"Human Development Index (HDI)","Unnamed: 4":"Life expectancy at birth","Unnamed: 6":"Expected years of schooling","Unnamed: 8":"Mean years of schooling","Unnamed: 10":"Gross national income (GNI) per capita","Unnamed: 12":"GNI per capita rank minus HDI rank	","Unnamed: 14":"HDI Rank"}
HDICleaned.rename(columns=change,inplace=True)
HDICleaned

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank\t,HDI Rank
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
columns = pd.MultiIndex.from_tuples([
    ('HDI rank', '', ''),
    ('Country', '', ''),
    ('Human Development Index (HDI)', 'Value', '2021'),
    ('Life expectancy at birth', 'Years', '2021'),
    ('Expected years of schooling', 'Years', '2021'),
    ('Mean years of schooling', 'Years', '2021'),
    ('Gross national income (GNI) per capita', '2017 PPP $', '2021'),
    ('GNI per capita rank minus HDI rank', '', '2021'),
    ('HDI Rank', '', '2020')
])

# Para reemplazar las columnas del DataFrame actual
HDICleaned.columns = columns

HDICleaned

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,,Value,Years,Years,Years,2017 PPP $,,
,,,2021,2021,2021,2021,2021,2021,2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
#Se reestablece el índice del dataframe
HDICleaned = HDICleaned.reset_index(drop=True)

#Se procede a eliminar las filas por su posición
HDICleaned = HDICleaned.drop(index=[0,1,2,3,4,5,6])

HDICleaned

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,,Value,Years,Years,Years,2017 PPP $,,
,,,2021,2021,2021,2021,2021,2021,2020
7,1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
8,2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
9,3,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
10,4,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
11,5,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
HDICleaned = HDICleaned.drop('HDI rank', axis=1)
HDICleaned

<ipython-input-92-ddab8697e50c>:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  HDICleaned = HDICleaned.drop('HDI rank', axis=1)

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
7,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
8,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
9,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
10,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
11,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...
271,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
#Se reseteó el número de índice para que empieze desde el 1.
HDICleaned.reset_index(drop=True, inplace=True)
HDICleaned.index += 1

HDICleaned

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
3,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
4,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
5,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...
265,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
#Se escogió solo a la lista de países
HDICleaned = HDICleaned.iloc[:199]


HDICleaned

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
3,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
4,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
5,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...
195,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Korea (Democratic People's Rep. of),..,"73,3","10,8",..,..,..,..
197,Monaco,..,"85,9",..,..,..,..,..
198,Nauru,..,"63,6","11,7",..,17.730,..,..
199,Somalia,..,"55,3",..,..,1.018,..,..

In [95]:
keywords = ["HIGH HUMAN DEVELOPMENT", "OTHER COUNTRIES OR TERRITORIES", "LOW HUMAN DEVELOPMENT"]
HDICleaned = HDICleaned[~HDICleaned['Country'].isin(keywords)]

HDICleaned

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
3,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
4,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
5,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...
194,South Sudan,"0,385","55,0","5,5","5,7",768,-1,191
196,Korea (Democratic People's Rep. of),..,"73,3","10,8",..,..,..,..
197,Monaco,..,"85,9",..,..,..,..,..
198,Nauru,..,"63,6","11,7",..,17.730,..,..
199,Somalia,..,"55,3",..,..,1.018,..,..

In [96]:
keep=[('Country', '', ''), ('Human Development Index (HDI)', 'Value', '2021'), ('Life expectancy at birth', 'Years', '2021'), ('Expected years of schooling', 'Years', '2021'), ('Mean years of schooling', 'Years', '2021'), ('Gross national income (GNI) per capita', '2017 PPP $', '2021'), ('GNI per capita rank minus HDI rank', '', '2021'), ('HDI Rank','','2020')]
HDICleaned=HDICleaned.loc[:,keep]
HDICleaned

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
3,Iceland,"0,959","82,7","19,2","13,8",55.782,11,2
4,"Hong Kong, China (SAR)","0,952","85,5","17,3","12,2",62.607,6,4
5,Australia,"0,951","84,5","21,1","12,7",49.238,18,5
...,...,...,...,...,...,...,...,...
194,South Sudan,"0,385","55,0","5,5","5,7",768,-1,191
196,Korea (Democratic People's Rep. of),..,"73,3","10,8",..,..,..,..
197,Monaco,..,"85,9",..,..,..,..,..
198,Nauru,..,"63,6","11,7",..,17.730,..,..
199,Somalia,..,"55,3",..,..,1.018,..,..

In [97]:
HDICleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 196 entries, 1 to 199
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   (Country, , )                                               196 non-null    object
 1   (Human Development Index (HDI), Value, 2021)                195 non-null    object
 2   (Life expectancy at birth, Years, 2021)                     195 non-null    object
 3   (Expected years of schooling, Years, 2021)                  195 non-null    object
 4   (Mean years of schooling, Years, 2021)                      195 non-null    object
 5   (Gross national income (GNI) per capita, 2017 PPP $, 2021)  195 non-null    object
 6   (GNI per capita rank minus HDI rank, , 2021)                195 non-null    object
 7   (HDI Rank, , 2020)                                          195 non-null    object
dtypes: object(8)
memory usage: 17.9+ KB

In [98]:
objectHDI=HDICleaned.select_dtypes(include=['object']).columns
objectHDI

MultiIndex([(                               'Country',           '',     ''),
            (         'Human Development Index (HDI)',      'Value', '2021'),
            (              'Life expectancy at birth',      'Years', '2021'),
            (           'Expected years of schooling',      'Years', '2021'),
            (               'Mean years of schooling',      'Years', '2021'),
            ('Gross national income (GNI) per capita', '2017 PPP $', '2021'),
            (    'GNI per capita rank minus HDI rank',           '', '2021'),
            (                              'HDI Rank',           '', '2020')],
           )

In [99]:
#Se reemplaza la coma por el punto para tener listas numéricas
HDICleaned[('Human Development Index (HDI)','Value','2021')]=HDICleaned[('Human Development Index (HDI)','Value','2021')].str.replace(",",'.')
HDICleaned[('Life expectancy at birth','Years','2021')]=HDICleaned[('Life expectancy at birth','Years','2021')].str.replace(",",'.')
HDICleaned[('Expected years of schooling','Years','2021')]=HDICleaned[('Expected years of schooling','Years','2021')].str.replace(",",'.')
HDICleaned[('Mean years of schooling','Years','2021')]=HDICleaned[('Mean years of schooling','Years','2021')].str.replace(",",'.')
HDICleaned

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI Rank
,,Value,Years,Years,Years,2017 PPP $,,
,,2021,2021,2021,2021,2021,2021,2020
1,Switzerland,0.962,84.0,16.5,13.9,66.933,5,3
2,Norway,0.961,83.2,18.2,13.0,64.660,6,1
3,Iceland,0.959,82.7,19.2,13.8,55.782,11,2
4,"Hong Kong, China (SAR)",0.952,85.5,17.3,12.2,62.607,6,4
5,Australia,0.951,84.5,21.1,12.7,49.238,18,5
...,...,...,...,...,...,...,...,...
194,South Sudan,0.385,55.0,5.5,5.7,768,-1,191
196,Korea (Democratic People's Rep. of),..,73.3,10.8,..,..,..,..
197,Monaco,..,85.9,..,..,..,..,..
198,Nauru,..,63.6,11.7,..,17.730,..,..
199,Somalia,..,55.3,..,..,1.018,..,..

In [100]:
HDICleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 196 entries, 1 to 199
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   (Country, , )                                               196 non-null    object
 1   (Human Development Index (HDI), Value, 2021)                195 non-null    object
 2   (Life expectancy at birth, Years, 2021)                     195 non-null    object
 3   (Expected years of schooling, Years, 2021)                  195 non-null    object
 4   (Mean years of schooling, Years, 2021)                      195 non-null    object
 5   (Gross national income (GNI) per capita, 2017 PPP $, 2021)  195 non-null    object
 6   (GNI per capita rank minus HDI rank, , 2021)                195 non-null    object
 7   (HDI Rank, , 2020)                                          195 non-null    object
dtypes: object(8)
memory usage: 17.9+ KB

In [101]:
HDICleaned[('Human Development Index (HDI)','Value','2021')] = pd.to_numeric(HDICleaned[('Human Development Index (HDI)','Value','2021')], errors='coerce')
HDICleaned[('Life expectancy at birth','Years','2021')] = pd.to_numeric(HDICleaned[('Life expectancy at birth','Years','2021')], errors='coerce')
HDICleaned[('Expected years of schooling','Years','2021')] = pd.to_numeric(HDICleaned[('Expected years of schooling','Years','2021')], errors='coerce')
HDICleaned[('Mean years of schooling','Years','2021')] = pd.to_numeric(HDICleaned[('Mean years of schooling','Years','2021')], errors='coerce')
HDICleaned[('Gross national income (GNI) per capita','2017 PPP $','2021')] = pd.to_numeric(HDICleaned[('Gross national income (GNI) per capita','2017 PPP $','2021')], errors='coerce')
HDICleaned[('GNI per capita rank minus HDI rank','','2021')] = pd.to_numeric(HDICleaned[('GNI per capita rank minus HDI rank','','2021')], errors='coerce')
HDICleaned[('HDI Rank','','2020')] = pd.to_numeric(HDICleaned[('HDI Rank','','2020')], errors='coerce')
# Para verificar los tipos de datos
print(HDICleaned.dtypes)

Country                                                      object
Human Development Index (HDI)           Value       2021    float64
Life expectancy at birth                Years       2021    float64
Expected years of schooling             Years       2021    float64
Mean years of schooling                 Years       2021    float64
Gross national income (GNI) per capita  2017 PPP $  2021    float64
GNI per capita rank minus HDI rank                  2021    float64
HDI Rank                                            2020    float64
dtype: object

In [119]:
HDICleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 196 entries, 1 to 199
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   (Country, , )                                               196 non-null    object
 1   (Human Development Index (HDI), Value, 2021)                190 non-null    float64
 2   (Life expectancy at birth, Years, 2021)                     194 non-null    float64
 3   (Expected years of schooling, Years, 2021)                  192 non-null    float64
 4   (Mean years of schooling, Years, 2021)                      190 non-null    float64
 5   (Gross national income (GNI) per capita, 2017 PPP $, 2021)  192 non-null    float64
 6   (GNI per capita rank minus HDI rank, , 2021)                190 non-null    float64
 7   (HDI Rank, , 2020)                                          190 non-null    float64
dtypes: float64(7), object(1)
memory usage: 17.9+ KB

In [122]:
import os

os.mkdir('data')

HDICleaned.to_csv(os.path.join("data","HDICleaned.csv"),index=False)